### PR TITLE
Improve test code

### PR DESCRIPTION
**Pull request by noplanman**
This PR now allows for local database tests to be configurable. Check the new constants in `phpunit.xml.dist`. Just copy it to `phpunit.xml` and adjust values to your local test environment.

A bunch of DocBlock fixes and test renames.
Also makes more use of TestHelpers class to facilitate entity testing.

### CODE REVIEW

**Comment by noplanman** [comment]
@akalongman @MBoretto @jacklul 

Have you looked at this at all yet? Would like to merge before carrying on with implementations, as there are a lot of code changes.

**Comment by MBoretto** [comment]
Hello, just scroll fast so far, in the weekend  I plan some time to review them, but if you want go ahead merge!

**Comment by noplanman** [comment]
I'll wait till the weekend, then either you merge or I'll merge next week 😊 

Thanks!

**Comment by MBoretto** [comment]
Great work!

**Pull request merged**
