### PR TITLE
Introducing db external connection

### PR DESCRIPTION
**Pull request by MBoretto**
Let you use DB.php with an external pdo connection

### CODE REVIEW

**Comment by vitalyzhakov** [comment]
Hello!
How I can use Postgres?

**Comment by MBoretto** [comment]
Seems supported from pdo !

**Comment by chuv1** [comment]
SQLite supported by PDO too, but I had no luck to make it work...
So MySQL is the only option, right?

**Comment by jacklul** [comment]
Wouldn't using external pdo connection be a 'hacky' way to use SQLite?

**Pull request merged**
