### PR TITLE
Utf8supportforcommand

### PR DESCRIPTION
**Pull request by CrazyRedScorp**
Support for unicode characters in commands. _(try number two)_

### CODE REVIEW

**Comment by CrazyRedScorp** [comment]
Again =((
Sorry.
How to delete this pull?

**Comment by noplanman** [comment]
This PR looked fine! Not sure why you closed it and deleted your branch 😕 
For your next one, you can remove the commented lines too! No need for those any more 😉

**Comment by CrazyRedScorp** [comment]
Fine?! I had a red message with the same error. Ok. I try again :)

**Comment by CrazyRedScorp** [comment]
I clicked restore branch and reopen pull request. Check it, please.

**Comment by noplanman** [comment]
Right, you can remove the commented lines, just delete them completely.

Then [check here](https://travis-ci.org/akalongman/php-telegram-bot/jobs/123155116#L302) to see why the automated tests failed.
We're using the [PSR2](http://www.php-fig.org/psr/psr-2/) standard for this library, which means that the way the code is styled is important.

**Comment by CrazyRedScorp** [comment]
Wow. I understand now. I will correct now. Thank you very much!

**Comment by MBoretto** [comment]
Thanks!

**Pull request merged**
