### PR TITLE
Update Request.php

### PR DESCRIPTION
**Pull request by Metallizzer**
Do not use CURLOPT_POST setting when using "getMe" method

### CODE REVIEW

**Comment by noplanman** [comment]
@Metallizzer 
Any reason why we should use GET here instead of POST? Please explain 😊 

Telegram supports both and it works perfectly fine with POST.

**Comment by Metallizzer** [comment]
@noplanman, when using POST request with 'getMe' method, result is
`<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>`
It's just me?

**Comment by noplanman** [comment]
Hmm, interesting. And with GET it returns the correct response?

Would you mind sharing the command that you're using it in so I can test your exact scenario, please?

**Comment by Metallizzer** [comment]
@noplanman,
```php
<?php
// Load composer
require __DIR__.'/vendor/autoload.php';

$API_KEY  = 'my_bot_api_key';
$BOT_NAME = 'name_of_my_bot';

try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);

    $result = Longman\TelegramBot\Request::getMe();

    var_dump($result);
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    echo $e->getMessage();
}
```
Result is:
> Telegram returned an invalid response! Please your bot name and api token.

Result of curl_exec in [Request.php:190](https://github.com/akalongman/php-telegram-bot/blob/master/src/Request.php#L190) I have given above

GET request returns correct result

**Comment by noplanman** [comment]
Using your exact code, it works for both GET and POST for me.

What version of the library are you using? The latest from the `master` branch?

**Comment by Metallizzer** [comment]
@noplanman 
```php
class Telegram
{
    /**
     * Version
     *
     * @var string
     */
    protected $version = '0.33.0';
```
installed with composer

```json
{
    "require": {
        "longman/telegram-bot": "@stable"
    },
    "config": {
        "optimize-autoloader": true
    }
}
```

**Comment by noplanman** [comment]
Ok, looks good.
Could you open your `phpinfo()` and let me know which PHP and cURL version you're using?

**Comment by Metallizzer** [comment]
@noplanman,
PHP 5.5.28
cURL 7.27.0

Just tried on another server, it works
PHP 5.5.9-1ubuntu4.17
cURL 7.35.0

**Comment by noplanman** [comment]
Ok, so it probably has to do with the cURL version.

Could you activate the debug log and post the debug response you get when calling `getMe()` please.
(add this before the call)
```php
$telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);

TelegramLog::initDebugLog($BOT_NAME . '_debug.log'); // Add this line!

$result = Longman\TelegramBot\Request::getMe();
```
❗ **remember to remove your bot API key!!**

**Comment by Metallizzer** [comment]
@noplanman 

> [2016-06-17 02:55:05] bot_log.DEBUG: Verbose curl output: * About to connect() to api.telegram.org port 443 (#0) *   Trying 149.154.167.200... * connected * Connected to api.telegram.org (149.154.167.200) port 443 (#0) * successfully set certificate verify locations: *   CAfile: /some_path/certs/curl-ca-bundle.crt   CApath: none * SSL connection using ECDHE-RSA-AES256-GCM-SHA384 * Server certificate: *    subject: OU=Domain Control Validated; CN=api.telegram.org *     start date: 2015-05 *   expire date: 2018-05 *      subjectAltName: api.telegram.org matched *      issuer: C=US; S *   SSL certificate verify ok. &gt; POST /bot*MY_TOKEN_HERE*/getMe HTTP/1.1 Host: api.telegram.org Accept: */* Content-Length: -1 Content-Type: application/x-www-form-urlencoded Expect: 100-continue  &lt; HTTP/1.1 400 Bad Request &lt; Server: nginx/1.10.0 &lt; Date: Fri, 17 Jun 2016 09:55:04 GMT &lt; Content-Type: text/html &lt; Content-Length: 173 &lt; Connection: close &lt; Access-Control-Allow-Origin: * &lt; Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection &lt;  * Closing connection #0   [] []

**Comment by noplanman** [comment]
Not sure exactly why this is happening, but will dig a bit deeper 😉 

Thanks for posting the issue! Making the library more robust one request at a time 😄

**Comment by Metallizzer** [comment]
I guess that does not work due to the fact that method 'getMe' has no parameters

**Comment by Metallizzer** [comment]
Slightly changed getMe method in [Request.php:326](https://github.com/akalongman/php-telegram-bot/blob/master/src/Request.php#L326)
```php
    /**
     * Get me
     *
     * @return mixed
     */
    public static function getMe()
    {
        return self::send('getMe', ['fake_param']);
    }
```
and it earned :wink:

**Comment by noplanman** [comment]
Brilliant!
If you could update your PR and point it towards the `develop` branch, I'll merge.

Also, if you could add a short comment and link to this PR above the `return self::send(...)` line, that would be great.

Thanks!

**Pull request closed without merging**
