### PR TITLE
Initial code cleanup of `DB.php`.

### PR DESCRIPTION
**Pull request by noplanman**
No functional changes, only slight modifications of documentation and code layout.

### CODE REVIEW

**Comment by MBoretto** [comment]
-Ok for alphabetical ordering!
-Ok for No empty line after <?php
-OK for 1 empty line after the file header

We can start inserting a simple header for each class like:
```
/**
 * Class ClassName.
 */
```
And leave the default header for each file! @akalongman  Do you agree with that?

I have a question, the file header is formatted  with:
```
/*
 *
 *
 */
```
Should instread like the other dockblock?
```
/**
 *
 *
 */
```

**Comment by akalongman** [comment]
No empty line after <?php ?
Please, follow the PSR-2 coding standard

**Comment by akalongman** [comment]
If php-cs passes with no notices, everything is ok

**Comment by MBoretto** [comment]
It seems so from the travis checks

**Comment by akalongman** [comment]
Nice. You are doing amazing job guys

**Comment by noplanman** [comment]
@akalongman Does the PSR-2 require an empty space after the `<?php`?
I've searched for PSR-2 "guides" but couldn't find anything regarding that.

Could you recommend a thorough read for me to learn? :blush:

Thanks!

**Comment by noplanman** [comment]
@MBoretto Yes, DocBlock format (`/**`) should be used for the headers, otherwise phpdoc will give a nice red bar saying `No summary was found for this file`.

Ok for leaving default file header!

**Pull request merged**
