### PR TITLE
Fixes for #331 and #332

### PR DESCRIPTION
**Pull request by jacklul**
Those are fixes I applied to my bots.

Fixes https://github.com/akalongman/php-telegram-bot/issues/331
Addresses latest API update causing library to throw exceptions (channel messages), mentioned https://github.com/akalongman/php-telegram-bot/issues/332

### CODE REVIEW

**Comment by noplanman** [comment]
@MBoretto have you had a look at this PR too?
@jacklul is this good to merge or more of a quick fix?

**Comment by jacklul** [comment]
I haven't been able to test it out with new changes because my local getUpdates test bot returns error on dev branch now: `PHP Fatal error:  Call to a member function getBody() on null in src\Request.php on line 227`

But following the logic in new ServerResponse it should be fine...

**Comment by MBoretto** [comment]
No I didn't look so far. @jacklul we need to align this with the new develop to fix the travis fail

**Comment by jacklul** [comment]
All should be good now!

**Comment by MBoretto** [comment]
yessss

**Comment by noplanman** [comment]
There seems to be another issue with this. Will need to find out the underlying issue here, pin point if-else exceptions aren't so super-duper-awesome...
```
PHP Fatal error:  Uncaught Error: Call to a member function getFrom() on null in /bot/vendor/longman/telegram-bot/src/Commands/SystemCommands/GenericmessageCommand.php:63
Stack trace:
#0 /bot/vendor/longman/telegram-bot/src/Commands/Command.php(132): Longman\TelegramBot\Commands\SystemCommands\GenericmessageCommand->execute()
#1 /bot/vendor/longman/telegram-bot/src/Telegram.php(465): Longman\TelegramBot\Commands\Command->preExecute()
#2 /bot/vendor/longman/telegram-bot/src/Telegram.php(434): Longman\TelegramBot\Telegram->executeCommand('genericmessage')
#3 /bot/vendor/longman/telegram-bot/src/Telegram.php(362): Longman\TelegramBot\Telegram->processUpdate(Object(Longman\TelegramBot\Entities\Update))
#4 /bot/hook.php(48): Longman\TelegramBot\Telegram->handle()
#5 {main}
  thrown in /bot/vendor/longman/telegram-bot/src/Commands/SystemCommands/GenericmessageCommand.php on line 63
```

**Comment by jacklul** [comment]
That's probably because we don't have ChannelmessageCommand.php and EditedchannelmessageCommand.php.

**Pull request merged**
